### ISSUE TITLE
Error: Lock file is already being held

### ISSUE THREAD

**Issue by autonome** [ipfs-shipyard/npm-on-ipfs#116]
Now that the service is back up (#115), I'm seeing a new error.

> (node:21553) UnhandledPromiseRejectionWarning: Error: Lock file is already being held

I see the log below, and long hangs periodically during execution, then more of the same errors, and then I force kill it.

<details>
<summary>Log:</summary>

twerkworker-5935:buttons dietrich$ npm-ipfs i hypersimple
superagent: Enable experimental feature http2
👩‍🚀 Starting local proxy
🚀 Server running on port 63344
🎁 Installing dependencies with /Users/dietrich/.npm-packages/bin/npm
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs22622a40
Swarm listening on /ip4/127.0.0.1/tcp/63347/ipfs/QmdUbfvZohU6F6e24MJU8R8NEhRFZPq1rGyP78uy8nsGw4
Swarm listening on /p2p-circuit/ipfs/QmdUbfvZohU6F6e24MJU8R8NEhRFZPq1rGyP78uy8nsGw4
Swarm listening on /p2p-circuit/ip4/127.0.0.1/tcp/63347/ipfs/QmdUbfvZohU6F6e24MJU8R8NEhRFZPq1rGyP78uy8nsGw4
🗂️  Loading registry index from https://registry.js.ipfs.iossion 2681a7af22622a40
☎️  Dialling registry mirror /ip4/35.178.192.119/tcp/10029/ipfs/Qmf5Rpj2FVVFnvReM7sdjrBTroVhwQSjUrkPbzo5XoVuiE,/dns4/registry.js.ipfs.io/tcp/10029/ipfs/Qmf5Rpj2FVVFnvReM7sdjrBTro
VhwQSjUrkPbzo5XoVuiE
📱️ Connected to registryrollbackFailedOptional: verb npm-session 2681a7af22622a40
📄 GET /hypersimple 200 8569msckFailedOptional: verb npm-session 2681a7af22622a40
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfsple@0.4.0 checking installable status
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
(node:21161) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:21161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rej
ecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21161) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process
 with a non-zero exit code.
(node:21161) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:21161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rej
ecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21161) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:21161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rej
ecting a promise which was not handled with .catch(). (rejection id: 3)
(node:21161) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:21161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rej
ecting a promise which was not handled with .catch(). (rejection id: 4)
⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ fetchMetadata: sill resolveWithNewModule hypersimple@0.4.0 checking installable status

(A COUPLE MINUTES OF HANG)

😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfs
😈 Spawning an in-process IPFS node using repo at /Users/dietrich/.jsipfsple@0.4.0 checking installable status
(node:21161) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:21161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:21161) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:21161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:21161) UnhandledPromiseRejectionWarning: Error: Lock file is already being held
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:21161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:21161) UnhandledPromiseRejectionWarning: Error: Lock file is already being heldcking installable status
    at options.fs.stat (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/proper-lockfile/lib/lockfile.js:68:47)
    at callback (/Users/dietrich/.npm-packages/lib/node_modules/ipfs-npm/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
(node:21161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ fetchMetadata: sill resolveWithNewModule hypersimple@0.4.0 checking installable status

(MORE HANG)

</details>

**Comment by achingbrain** [comment]
Are you running an IPFS daemon at the same time?

**Comment by autonome** [comment]
Looks like that'll be resolved(-ish) by #113.

Using npm-on-ipfs is pretty much not possible until that's fixed, afaict?
