### ISSUE TITLE
NPM on IPFS cannot be installed on macOS Catalina

### ISSUE THREAD

**Issue by rex4539** [ipfs-shipyard/npm-on-ipfs#119]
```
3054 warn checkPermissions Missing write access to /usr/local/lib/node_modules
3055 timing stage:rollbackFailedOptional Completed in 0ms
3056 timing stage:runTopLevelLifecycles Completed in 21706ms
3057 verbose stack Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
3058 verbose cwd /Users/rex/ipfs-desktop
3059 verbose Darwin 19.0.0
3060 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ipfs-npm"
3061 verbose node v12.11.1
3062 verbose npm  v6.11.3
3063 error code EACCES
3064 error syscall access
3065 error path /usr/local/lib/node_modules
3066 error errno -13
3067 error Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
3067 error  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules'] {
3067 error   stack: "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
3067 error   errno: -13,
3067 error   code: 'EACCES',
3067 error   syscall: 'access',
3067 error   path: '/usr/local/lib/node_modules'
3067 error }
3068 error The operation was rejected by your operating system.
3068 error It is likely you do not have the permissions to access this file as the current user
3068 error
3068 error If you believe this might be a permissions issue, please double-check the
3068 error permissions of the file and its containing directories, or try running
3068 error the command again as root/Administrator.
3069 verbose exit [ -13, true ]
```

<img width="718" alt="Screenshot 2019-10-19 at 14 48 03" src="https://user-images.githubusercontent.com/227442/67144514-d03df300-f27f-11e9-948e-247ff9be9fae.png">

I tried to do manual install but that failed as well...

**Comment by hacdias** [comment]
Although I think this is _just_ a permissions error, I'm moving this to `npm-on-ipfs` repository where you can get more help. On my case, I'm using Catalina and I have no issues related to permissions. However, my `npm` installation does not install to `/usr/local/bin` which usually is more protected.

I will note that the install on my computer also logs errors even though it ends up installing correctly:

```
../src/rabin_wrap.cc:11:56: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    uint8_t *buf = (uint8_t*) node::Buffer::Data(bufs->Get(i));
                                                       ^
/Users/henriquedias/Library/Caches/node-gyp/12.8.0/include/node/v8.h:3423:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/henriquedias/Library/Caches/node-gyp/12.8.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/rabin_wrap.cc:12:42: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    int len = node::Buffer::Length(bufs->Get(i));
                                         ^
/Users/henriquedias/Library/Caches/node-gyp/12.8.0/include/node/v8.h:3423:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/henriquedias/Library/Caches/node-gyp/12.8.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/rabin_wrap.cc:24:16: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
      lengths->Set(chunk_idx++, Nan::New<Number>(hasher->chunk_length));
               ^
/Users/henriquedias/Library/Caches/node-gyp/12.8.0/include/node/v8.h:3374:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/henriquedias/Library/Caches/node-gyp/12.8.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
../src/rabin_wrap.cc:52:47: error: too few arguments to function call, single argument 'context' was not specified
  handle->average_bits = info[0]->Uint32Value();
                         ~~~~~~~~~~~~~~~~~~~~ ^
/Users/henriquedias/Library/Caches/node-gyp/12.8.0/include/node/v8.h:2574:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/henriquedias/Library/Caches/node-gyp/12.8.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/rabin_wrap.cc:53:42: error: too few arguments to function call, single argument 'context' was not specified
  handle->minsize = info[1]->Uint32Value();
                    ~~~~~~~~~~~~~~~~~~~~ ^
/Users/henriquedias/Library/Caches/node-gyp/12.8.0/include/node/v8.h:2574:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/henriquedias/Library/Caches/node-gyp/12.8.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/rabin_wrap.cc:54:42: error: too few arguments to function call, single argument 'context' was not specified
  handle->maxsize = info[2]->Uint32Value();
                    ~~~~~~~~~~~~~~~~~~~~ ^
/Users/henriquedias/Library/Caches/node-gyp/12.8.0/include/node/v8.h:2574:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/henriquedias/Library/Caches/node-gyp/12.8.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
3 warnings and 3 errors generated.
make: *** [Release/obj.target/rabin/src/rabin_wrap.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/12.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/henriquedias/.npm-global/lib/node_modules/ipfs-npm/node_modules/rabin
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: rabin@1.6.0 (node_modules/ipfs-npm/node_modules/rabin):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: rabin@1.6.0 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by hacdias** [comment]
@rex4539 I see you already had opened an issue here #118. I'm closing that one since this once has more details.

**Comment by wiktoriatomzik** [comment]
Similar error here, macOS Catalina, anyone has a clue what can be done with this?

**Comment by JohnKnust** [comment]
Hi guys, I run on mac OS BigSure 11.2.1 (20D74) into the same problem and found a solution.

First I was using the installer from node webpage, guess this was the first problem because everything was created as root.
According to your error: 

```bash
3067 error Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
```

I first solved it partly by changing the ownership as described here: [stackoverflow.com](https://stackoverflow.com/questions/48910876/error-eacces-permission-denied-access-usr-local-lib-node-modules#)
Next, npm raised new errors.

I left the system's installation as followed [a guide to install via nvm](https://ourcodeworld.com/articles/read/1429/how-to-install-nodejs-in-macos-bigsur). I hit enter for the install -g ipfs command again, and it worked like a charm.

```javascript
npm WARN ipfs-daemon@0.5.2 requires a peer of electron-webrtc@^0.3.0, but none is installed. You must install peer dependencies yourself.
npm WARN ipfs-daemon@0.5.2 requires a peer of wrtc@^0.4.6, but none is installed. You must install peer dependencies yourself.
npm WARN prometheus-gc-stats@0.6.3 requires a peer of prom-client@>= 10 <= 12, but none is installed. You must install peer dependencies yourself.

+ ipfs@0.54.2
added 818 packages from 1221 contributors in 87.756s
```
