### ISSUE TITLE
Error: Cannot find module 'multicodec/src/name-table'

### ISSUE THREAD

**Issue by kumavis** [ipfs-shipyard/npm-on-ipfs#124]
just encountered this with
``` bash
npm i -g ipfs
npm i -g ipfs-npm
jsipfs init
ipfs-npm --package-manager=yarn
```

```
metamask-extension on  develop [$!] is 📦 v0.0.0 via ⬢ v10.17.0 
⇡0% ➜ ipfs-npm --package-manager=yarn
👩‍🚀 Starting local proxy
🚀 Server running on port 41037
🎁 Installing dependencies with /home/xyz/.yarn/bin/yarn
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
⠁ 😈 Spawning an in-process IPFS node using repo at /home/xyz/.jsipfs
⡀ minimist@^1.2.5(node:28007) UnhandledPromiseRejectionWarning: Error: Cannot find module 'multicodec/src/name-table'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/xyz/.nvm/versions/node/v10.17.0/lib/node_modules/ipfs-npm/node_modules/ipfs-bitswap/src/types/message/index.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/xyz/.nvm/versions/node/v10.17.0/lib/node_modules/ipfs-npm/node_modules/ipfs-bitswap/src/want-manager/index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/xyz/.nvm/versions/node/v10.17.0/lib/node_modules/ipfs-npm/node_modules/ipfs-bitswap/src/index.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
(node:28007) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:28007) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠠ minimist@^1.2.5^C%                                    
```

**Comment by kumavis** [comment]
cc @alanshaw
relevant https://github.com/ipfs/js-ipfs/issues/2700

**Comment by obernardovieira** [comment]
Hi,
I'm having the same issue.
Any solution?

**Comment by leonardge** [comment]
Same here.

**Comment by leonardge** [comment]
I think upgrade the `ipfs` and `ipfsd-ctl` version should solve the problem. And as part of the update you might need to change the `ipfsd-ctl` API that is been called.
