### ISSUE TITLE
Print more friendly error or offer to spin a go-ipfs or js-ipfs daemon

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/npm-on-ipfs#59]
Currently, this is what a user get if it doesn't has go-ipfs running.
```
» ipfs-npm daemon
{ Error: connect ECONNREFUSED 127.0.0.1:5001
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5001,
  trace:
   [ { method: 'GET',
       url: 'http://127.0.0.1:5001/api/v0/swarm/connect?arg=%2Fip4%2F188.40.114.11%2Ftcp%2F8801%2Fipfs%2FQmToeN85brexqyXUnWnKfHFqhvucJPViw9AxQQkjLoULy4&stream-channels=true' } ],
  isBoom: true,
  isServer: true,
  data: null,
  output:
   { statusCode: 502,
     payload:
      { statusCode: 502,
        error: 'Bad Gateway',
        message: 'connect ECONNREFUSED 127.0.0.1:5001' },
     headers: {} },
  reformat: [Function] }
```

**Comment by achingbrain** [comment]
Weird, it should spin up an IPFS node in the background automatically if you don't use the `--ipfs-port` and optionally the `--ipfs-host` args.

**Comment by diasdavid** [comment]
Got it. The module hasn't been published -- https://www.npmjs.com/package/ipfs-npm I installed the old old version. 

Why hasn't it been released?
