### ISSUE TITLE
request to https://localhost/chunky/-/chunky-0.0.0.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/npm-on-ipfs#72]
This is `npm i` in js-ipfs project:

```console
# ...
npm http fetch GET 304 https://registry.js.ipfs.io/has-values 1937ms (from cache)
npm http fetch GET 200 https://registry.js.ipfs.io/escodegen 2198ms
npm http fetch GET 304 https://registry.js.ipfs.io/idb-readable-stream 1493ms (from cache)
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://localhost/chunky/-/chunky-0.0.0.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:443
npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:182:13)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:391:9)
npm ERR!     at TLSSocket.emit (events.js:182:13)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:82:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR!  { FetchError: request to https://localhost/chunky/-/chunky-0.0.0.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:443
npm ERR!     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:182:13)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:391:9)
npm ERR!     at TLSSocket.emit (events.js:182:13)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:82:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR!   message:
npm ERR!    'request to https://localhost/chunky/-/chunky-0.0.0.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:443',
npm ERR!   type: 'system',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   stack:
npm ERR!    'FetchError: request to https://localhost/chunky/-/chunky-0.0.0.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:443\n    at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)\n    at ClientRequest.emit (events.js:182:13)\n    at TLSSocket.socketErrorListener (_http_client.js:391:9)\n    at TLSSocket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)',
npm ERR!   parent: 'libp2p-mplex' }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alan/.npm/_logs/2018-10-19T08_55_18_922Z-debug.log
```

**Comment by achingbrain** [comment]
Good spot, thanks!  Fixed in https://github.com/ipfs-shipyard/ipfs-registry-mirror/commit/7bb463ad1c51cfb88b09049cc56c41cf8039c373
