### ISSUE TITLE
500 Internal Server Error: chunkd@^1.0.0

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/npm-on-ipfs#73]
```console
826 verbose stack Error: 500 Internal Server Error: chunkd@^1.0.0
826 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
826 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
826 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
826 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
826 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
826 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
826 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
826 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
826 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
826 verbose stack     at runCallback (timers.js:705:18)
826 verbose stack     at tryOnImmediate (timers.js:676:5)
826 verbose stack     at processImmediate (timers.js:658:5)
```

and then retrying:

```console
817 verbose type system
818 verbose stack FetchError: request to https://registry.js.ipfs.io/chunkd failed, reason: getaddrinfo ENOTFOUND registry.js.ipfs.io registry.js.ipfs.io:443
818 verbose stack     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
818 verbose stack     at ClientRequest.emit (events.js:182:13)
818 verbose stack     at TLSSocket.socketErrorListener (_http_client.js:391:9)
818 verbose stack     at TLSSocket.emit (events.js:182:13)
818 verbose stack     at emitErrorNT (internal/streams/destroy.js:82:8)
818 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
818 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
819 verbose cwd /Users/alan/Code/fun/abortable-iterator
820 verbose Darwin 18.0.0
821 verbose argv "/usr/local/Cellar/node/10.12.0/bin/node" "/usr/local/bin/npm" "i" "ava@1.0.0-rc.1" "--save-dev"
822 verbose node v10.12.0
823 verbose npm  v6.4.1
```

**Comment by achingbrain** [comment]
This should be fixed in ipfs-shipyard/ipfs-npm-registry-mirror@e6f4dd5  Turns out not every npm module has a `_rev` property 🙄  I guess the underscore should have been a giveaway.

The error while retrying looks like a DNS failure?
