### ISSUE TITLE
EINVALIDTAGNAME

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/npm-on-ipfs#84]
```console
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "listr-verbose-renderer@~0.4.1": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alan/.npm/_logs/2019-01-29T15_25_54_499Z-debug.log
```

**Comment by achingbrain** [comment]
How did you get this error?  I've tried:

```
ipfs-npm install listr-verbose-renderer@0.4.1
```

and

```
ipfs-npm install listr-verbose-renderer@~0.4.1
```

and also installing from a `package.json` with `listr-verbose-renderer` using `~0.4.1` as the version number but didn't get an error.

**Comment by alanshaw** [comment]
`npm i --production` in `libp2p-crypto`

```console
3644 verbose stack Error: Invalid tag name "listr-verbose-renderer@~0.4.1": Tags may not have any characters that encodeURIComponent encodes.
3644 verbose stack     at invalidTagName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:87:15)
3644 verbose stack     at fromRegistry (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:290:13)
3644 verbose stack     at Function.resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:77:12)
3644 verbose stack     at doesChildVersionMatch (/usr/local/lib/node_modules/npm/lib/install/deps.js:75:25)
3644 verbose stack     at isDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:147:27)
3644 verbose stack     at addRequiredDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:159:13)
3644 verbose stack     at addBundled (/usr/local/lib/node_modules/npm/lib/install/deps.js:674:7)
3644 verbose stack     at addBundled (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:93:78)
3644 verbose stack     at isInstallable (/usr/local/lib/node_modules/npm/lib/install/deps.js:652:5)
3644 verbose stack     at checkPlatform (/usr/local/lib/node_modules/npm/node_modules/npm-install-checks/index.js:53:10)
3644 verbose stack     at thenWarnEngineIssues (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:52:5)
3644 verbose stack     at a (/usr/local/lib/node_modules/npm/node_modules/iferr/iferr.js:3:64)
3644 verbose stack     at checkEngine (/usr/local/lib/node_modules/npm/node_modules/npm-install-checks/index.js:24:10)
3644 verbose stack     at module.exports.isInstallable (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:49:3)
3644 verbose stack     at resolveWithNewModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:650:10)
3644 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:573:7
3645 verbose cwd /Users/alan/Code/protocol-labs/js-libp2p-crypto
3646 verbose Darwin 18.2.0
3647 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--production"
3648 verbose node v11.6.0
3649 verbose npm  v6.5.0-next.0
3650 error code EINVALIDTAGNAME
3651 error Invalid tag name "listr-verbose-renderer@~0.4.1": Tags may not have any characters that encodeURIComponent encodes.
```

**Comment by alanshaw** [comment]
no longer reproduces
